=begin
#EDINET API

#EDINET API は、利用者が EDINET の画面からではなく、プログラムを介して EDINET のデータベースから効率的にデータを取得できる API(アプリケーション・プログラミング・インターフェース)です。EDINET API により、EDINET 利用者は効率的に開示情報を取得することが可能となります。

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'spec_helper'
require 'json'

# Unit tests for EdinetAPIClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = EdinetAPIClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(EdinetAPIClient::DefaultApi)
    end
  end

  # unit tests for find_documents
  # 書類一覧 API
  # 書類一覧 API では、「メタデータのみ」または「提出書類一覧及びメタデータ」を取得することが可能です。
  # @param date 出力対象とする提出書類一覧のファイル日付（YYYY-MM-DD形式）を指定します。
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :type 取得情報を指定します。  * 1: メタデータのみを取得します。  * 2: 提出書類一覧及びメタデータを取得します。 
  # @return [InlineResponse200]
  describe 'find_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_document
  # 書類取得 API
  # 書類取得 API では、書類をダウンロードすることが可能です。
  # @param doc_id 取得したい書類の書類管理番号を指定します（書類管理番号は、書類一覧 API で取得した提出書類一覧に基づきます。ただし、開示対象外の書類は取得できません）。
  # @param type 必要書類を指定します。  * 1: 提出本文書及び監査報告書を取得します。  * 2: PDF を取得します。  * 3: 代替書面・添付文書を取得します。  * 4: 英文ファイルを取得します。 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
