=begin
#EDINET API

#EDINET API は、利用者が EDINET の画面からではなく、プログラムを介して EDINET のデータベースから効率的にデータを取得できる API(アプリケーション・プログラミング・インターフェース)です。EDINET API により、EDINET 利用者は効率的に開示情報を取得することが可能となります。

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

# Common files
require 'edinet_api_client/api_client'
require 'edinet_api_client/api_error'
require 'edinet_api_client/version'
require 'edinet_api_client/configuration'

# Models
require 'edinet_api_client/models/document'
require 'edinet_api_client/models/inline_response200'
require 'edinet_api_client/models/metadata'
require 'edinet_api_client/models/metadata_parameter'
require 'edinet_api_client/models/metadata_resultset'

# APIs
require 'edinet_api_client/api/default_api'

module EdinetAPIClient
  class << self
    # Customize default settings for the SDK using block.
    #   EdinetAPIClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
